### PR TITLE
Update streamr-client (→ v5.4.4)

### PR DESCRIPTION
**Pull request by mondoreale**
All should be good here. @juhah please throw a quick eye; merge if like, too. Overall no-biggie. Cheers!

### CODE REVIEW

**Comment by juhah** [comment]
I am getting an error when switching from "24 hours" stream to "1 month":

https://user-images.githubusercontent.com/1064982/122879171-47733680-d341-11eb-965f-badd8ac7c79a.mov

Old client version (`master`) works ok so something is happening in the new client.

**Comment by mondoreale** [comment]
Thanks @juhah, very good catch. Will fix.

**Comment by mondoreale** [comment]
@juhah I updated both `streamr-client` and `streamr-client-react` (missed the other one before). It's should be fine now. Can you throw an eye one more time?

**Comment by mondoreale** [comment]
@juhah, now it should be able to fly pretty far. Fixed the stagnation issue (no data coming through). Please have a quick look whenever convenient.

**Review by juhah — APPROVED** [review]
Great, seems to work nicely now 👍

**Pull request merged**
